### ISSUE TITLE
Design Requirements

### ISSUE THREAD

**Issue by TFisch** [TFisch/dm-tf-weathrly#1]
**Phase I**

- [x] Create User Interface using mock data. 

Current weather component should display the following information,

- [x] Name of the current city
- [x] Current condition
- [x] Current day
- [x] Current temperature
- [x] Expected high and expected low for the day
- [x] Summary of what the weather is going to be like that day (“Windy, chance of a few late night showers. Lows overnight in the mid 50s.)

**Phase II**

Application should have a 7 hour weather forecast component. Each hour should be a card component and should display,
- [x] The hour
- [x] Image that reflects the weather
- [x] Projected temperature

- [x] Application should handle when a user searches for a location that is not found by the API. Team should research different ways to handle unfound locations by looking around on different weather and other location searching applications and implement a solution for their project that they find intuitive.

**Phase III**

The application should have a 10 day forecast component. Each day should be a card component and should display
- [x] the name of the day
- [x] an image that reflects the weather
- [x] the projected high and low temperature

**Phase IV**

- [x] Application has a welcome page that greets the user. 
- [x] The welcome page has a search component.
- [x] The search component consists of an input field and a submit button that allows the user to search for a location.
- [x] the location should work with both a zip code and city/state.
- [x] Once the desired location is submitted there should be a way for the user to change location information.
- [x]  Once the location information is changed the weather should reflect the desired location.
- [x] location persists after refresh.

**Phase V**

- [x] Add autocomplete functionality to search input
- [x] Populate list of city/states using data trie. 
- [x] When a user starts typing in a city/state or zip code display a list of possible suggestions using data trie function.
